#!/usr/bin/ruby

require 'Qt4'
require 'xmmsclient/async'

require './xmmsclient-qt4'


# TODO:
# - use columns to separate fields
# - type in playlist to filter playlist entries (custom search)
# - actions should report a status message
# - reuse search results (activate to play, enqueue, copy, etc)
# - rerequest entry metadata if not resolved yet
# - lazy loading, only visible entries
# - playlist: delete, move (ctrl+arrow) entries with keyboard

# FIXME: ugly way to load libs from src/
$:.push("src")

require 'lindale.rb'
require 'panes/playlist.rb'
require 'panes/search.rb'
require 'panes/control.rb'

require 'cache.rb'


app = Qt::Application.new(ARGV)

xc = Xmms::Client::Async.new("lindale")
xc.connect(ENV["XMMS_PATH"])
xc.add_to_qt4_mainloop

cache = Xmms2Cache.new(xc)

# teh app
lindale = Lindale.new

# prepare panes
playlist = Playlist.new(xc, cache)
search = Search.new(xc, cache)
ctrl = Control.new(xc, cache)

# register commands
lindale.add_command('list', playlist)
lindale.add_command('search', search)
lindale.add_command('play', ctrl, :play)
lindale.add_command('pause', ctrl, :pause)
lindale.add_command('stop', ctrl, :stop)
lindale.add_command('p', ctrl, :toggleplay)
lindale.add_alias('search', 's', '?')


mainwin = Qt::MainWindow.new
mainwin.setCentralWidget(lindale)
mainwin.setWindowTitle("lindalë")
mainwin.show

app.exec()
